# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UvoMddQ9B5Ud9alXuoh-AIKP7hUzr0zE
"""

data_1 = input("Birinci değeri giriniz:")
data_2 = input("İkinci değeri giriniz:")
data_3 = input("Üçüncü değeri giriniz:")
data_4 = input("Dördüncü değeri giriniz:")
data_5 = input("Beşinci değeri giriniz:")

print("----------------------------------")

print("Girdiğiniz veriler sırasıyla= {},{},{},{},{}'dır.".format(data_1,data_2,data_3,data_4,data_5))

print("""
Girdiğiniz verilerin türü sırasıyla {} - {} - {} - {} - {} ' dır.""". format(type(data_1),type(data_2),type(data_3),type(data_4),type(data_5)))